### 1. Import Library

In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, Imputer
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
from sklearn.model_selection import train_test_split
import sys 
import os
sys.path.append(os.path.abspath("C:/Users/Wahyu Nainggolan/Documents/TA Gue/TA_2/Implementasi/fix/preprocessing_data"))
from preprocessing_data import preprocessingData
from preprocessing_data import preprocessingData_onehotencoder

### 2. Calling Data

In [23]:
world_cup_2014 = pd.read_csv("C:/Users/Wahyu Nainggolan/Documents/TA Gue/TA_2/Implementasi/Data/2014/data_train/data_full_2014.csv", delimiter= ',')
data_test_world_cup_2014 = pd.read_csv("C:/Users/Wahyu Nainggolan/Documents/TA Gue/TA_2/Implementasi/Data/2014/data_test/data_test.csv", delimiter= ',')

### 3. Description Data

3.1. Ukuran Data

In [24]:
print('Ukuran data train',world_cup_2014.shape)
print('Ukuran data test',data_test_world_cup_2014.shape)

Ukuran data train (1267, 23)
Ukuran data test (46, 23)

3.2. Parameter yang ada pada Data

In [25]:
# Data Training
world_cup_2014.columns

Index(['home_team', 'away_team', 'home_score', 'away_score', 'Hasil', 'HTRF',
       'THFP', 'PHPAR', 'PHSPAR', 'PHPSAR', 'PHDAR', 'PHTSA', 'PHDBAR',
       'PHAAR', 'ATRF', 'TAFP', 'PAPAR', 'PASPAR', 'PAPSAR', 'PADAR', 'PATSA',
       'PADBAR', 'PAAAR'],
      dtype='object')

In [26]:
# Data Testing 
data_test_world_cup_2014.columns

Index(['home_team', 'away_team', 'home_score', 'away_score', 'Hasil', 'HTRF',
       'THFP', 'PHPAR', 'PHSPAR', 'PHPSAR', 'PHDAR', 'PHTSA', 'PHDBAR',
       'PHAAR', 'ATRF', 'TAFP', 'PAPAR', 'PASPAR', 'PAPSAR', 'PADAR', 'PATSA',
       'PADBAR', 'PAAAR'],
      dtype='object')

3.3. Bentuk Data

In [27]:
print("10 Data Train Pertama :")
world_cup_2014.head(10)

10 Data Train Pertama :

,home_team,away_team,home_score,away_score,Hasil,HTRF,THFP,PHPAR,PHSPAR,PHPSAR,...,PHAAR,ATRF,TAFP,PAPAR,PASPAR,PAPSAR,PADAR,PATSA,PADBAR,PAAAR
0,Greece,Korea Republic,1,1,Draw,18.0,3.0,73.0,66.0,79.0,...,28.0,56.0,9.0,72.0,67.0,78.0,62.0,77.0,73.0,26.0
1,Nigeria,Ghana,1,0,Home_win,33.0,5.0,70.0,64.0,80.0,...,25.0,23.0,3.0,71.0,66.0,80.0,63.0,81.0,74.0,25.0
2,Cameroon,Ivory Coast,1,1,Draw,59.0,7.0,69.0,64.0,81.0,...,26.0,17.0,3.0,72.0,65.0,80.0,62.0,80.0,73.0,27.0
3,Nigeria,Ivory Coast,0,1,Away_win,33.0,5.0,70.0,64.0,80.0,...,25.0,17.0,3.0,72.0,65.0,80.0,62.0,80.0,73.0,27.0
4,USA,Japan,3,2,Home_win,31.0,10.0,70.0,66.0,80.0,...,27.0,44.0,5.0,72.0,66.0,74.0,63.0,73.0,72.0,27.0
5,Costa Rica,Korea Republic,1,0,Home_win,13.0,4.0,66.0,60.0,76.0,...,27.0,56.0,9.0,72.0,67.0,78.0,62.0,77.0,73.0,26.0
6,Mexico,Korea Republic,0,1,Away_win,24.0,15.0,71.0,64.0,75.0,...,27.0,56.0,9.0,72.0,67.0,78.0,62.0,77.0,73.0,26.0
7,Bosnia-Herzegovina,Japan,2,2,Draw,16.0,1.0,73.0,66.0,79.0,...,27.0,44.0,5.0,72.0,66.0,74.0,63.0,73.0,72.0,27.0
8,England,Uruguay,2,1,Home_win,10.0,14.0,75.0,68.0,81.0,...,26.0,6.0,12.0,72.0,66.0,80.0,65.0,77.0,74.0,28.0
9,Iran,Costa Rica,3,2,Home_win,49.0,4.0,67.0,60.0,75.0,...,28.0,13.0,4.0,66.0,60.0,76.0,57.0,74.0,67.0,27.0

In [28]:
print("10 Data Test Pertama :")
data_test_world_cup_2014.head(10)

10 Data Test Pertama :

,home_team,away_team,home_score,away_score,Hasil,HTRF,THFP,PHPAR,PHSPAR,PHPSAR,...,PHAAR,ATRF,TAFP,PAPAR,PASPAR,PAPSAR,PADAR,PATSA,PADBAR,PAAAR
0,Brazil,Colombia,2,1,Home_win,11.0,20.0,76.0,70.0,80.0,...,28.0,4.0,5.0,73.0,67.0,80.0,63.0,79.0,75.0,27.0
1,Mexico,Cameroon,1,0,Home_win,24.0,15.0,71.0,64.0,75.0,...,27.0,59.0,7.0,69.0,64.0,81.0,63.0,81.0,74.0,26.0
2,Spain,Netherlands,1,5,Away_win,1.0,14.0,81.0,71.0,79.0,...,28.0,8.0,10.0,74.0,68.0,80.0,63.0,78.0,75.0,26.0
3,Chile,Australia,3,1,Home_win,12.0,9.0,73.0,68.0,76.0,...,28.0,57.0,4.0,71.0,64.0,78.0,62.0,76.0,71.0,26.0
4,Colombia,Greece,3,0,Home_win,4.0,5.0,73.0,67.0,80.0,...,27.0,18.0,3.0,73.0,66.0,79.0,62.0,76.0,74.0,28.0
5,Uruguay,Costa Rica,1,3,Away_win,6.0,12.0,72.0,66.0,80.0,...,28.0,13.0,4.0,66.0,60.0,76.0,57.0,74.0,67.0,27.0
6,England,Italy,1,2,Away_win,10.0,14.0,75.0,68.0,81.0,...,26.0,9.0,18.0,76.0,68.0,81.0,66.0,77.0,75.0,27.0
7,Ivory Coast,Japan,2,1,Home_win,17.0,3.0,72.0,65.0,80.0,...,27.0,44.0,5.0,72.0,66.0,74.0,63.0,73.0,72.0,27.0
8,Switzerland,Ecuador,2,1,Home_win,7.0,10.0,72.0,66.0,80.0,...,26.0,22.0,3.0,70.0,65.0,77.0,57.0,80.0,75.0,27.0
9,France,Honduras,3,0,Home_win,21.0,14.0,76.0,69.0,80.0,...,26.0,34.0,3.0,70.0,62.0,78.0,60.0,77.0,72.0,28.0

### 4. Prepare Data

In [29]:
null_counts_data_train = world_cup_2014.isnull().sum()
print("Jumlah data yang kosong pada data training:\n{}".format(null_counts_data_train))

Jumlah data yang kosong pada data training:
home_team      0
away_team      0
home_score     0
away_score     0
Hasil          0
HTRF          11
THFP          11
PHPAR         11
PHSPAR        13
PHPSAR        12
PHDAR         11
PHTSA         12
PHDBAR        14
PHAAR         12
ATRF          13
TAFP          13
PAPAR         14
PASPAR        15
PAPSAR        13
PADAR         13
PATSA         19
PADBAR        17
PAAAR         20
dtype: int64

In [30]:
null_counts_data_train = data_test_world_cup_2014.isnull().sum()
print("Jumlah data yang kosong pada data training:\n{}".format(null_counts_data_train))

Jumlah data yang kosong pada data training:
home_team     0
away_team     0
home_score    0
away_score    0
Hasil         0
HTRF          1
THFP          1
PHPAR         1
PHSPAR        1
PHPSAR        1
PHDAR         1
PHTSA         1
PHDBAR        1
PHAAR         1
ATRF          3
TAFP          3
PAPAR         3
PASPAR        3
PAPSAR        3
PADAR         3
PATSA         3
PADBAR        3
PAAAR         3
dtype: int64

In [31]:
independent_data_train,dependent_data_train= preprocessingData(world_cup_2014)

[SoftImpute] Max Singular Value of X_init = 9018.330747
[SoftImpute] Iter 1: observed MAE=2.260309 rank=6
[SoftImpute] Iter 2: observed MAE=2.204391 rank=5
[SoftImpute] Iter 3: observed MAE=2.197538 rank=5
[SoftImpute] Iter 4: observed MAE=2.202946 rank=5
[SoftImpute] Iter 5: observed MAE=2.212956 rank=5
[SoftImpute] Iter 6: observed MAE=2.227838 rank=5
[SoftImpute] Iter 7: observed MAE=2.247146 rank=5
[SoftImpute] Iter 8: observed MAE=2.260680 rank=5
[SoftImpute] Iter 9: observed MAE=2.261968 rank=5
[SoftImpute] Iter 10: observed MAE=2.259565 rank=5
[SoftImpute] Iter 11: observed MAE=2.257570 rank=5
[SoftImpute] Iter 12: observed MAE=2.256382 rank=5
[SoftImpute] Iter 13: observed MAE=2.255731 rank=5
[SoftImpute] Iter 14: observed MAE=2.255385 rank=5
[SoftImpute] Iter 15: observed MAE=2.255203 rank=5
[SoftImpute] Stopped after iteration 15 for lambda=180.366615

C:\Users\Wahyu Nainggolan\Anaconda3\lib\site-packages\fancyimpute\soft_impute.py:100: RuntimeWarning: divide by zero encountered in double_scalars
  return (np.sqrt(ssd) / old_norm) < self.convergence_threshold

In [32]:
independent_data_train.head(10)

,home_team,away_team,home_score,away_score,HTRF,THFP,PHPAR,PHSPAR,PHPSAR,PHDAR,...,PHAAR,ATRF,TAFP,PAPAR,PASPAR,PAPSAR,PADAR,PATSA,PADBAR,PAAAR
0,Greece,Korea Republic,1,1,18.0,3.0,73.0,66.0,79.0,62.0,...,28.0,56.0,9.0,72.0,67.0,78.0,62.0,77.0,73.0,26.0
1,Nigeria,Ghana,1,0,33.0,5.0,70.0,64.0,80.0,61.0,...,25.0,23.0,3.0,71.0,66.0,80.0,63.0,81.0,74.0,25.0
2,Cameroon,Ivory Coast,1,1,59.0,7.0,69.0,64.0,81.0,63.0,...,26.0,17.0,3.0,72.0,65.0,80.0,62.0,80.0,73.0,27.0
3,Nigeria,Ivory Coast,0,1,33.0,5.0,70.0,64.0,80.0,61.0,...,25.0,17.0,3.0,72.0,65.0,80.0,62.0,80.0,73.0,27.0
4,USA,Japan,3,2,31.0,10.0,70.0,66.0,80.0,62.0,...,27.0,44.0,5.0,72.0,66.0,74.0,63.0,73.0,72.0,27.0
5,Costa Rica,Korea Republic,1,0,13.0,4.0,66.0,60.0,76.0,57.0,...,27.0,56.0,9.0,72.0,67.0,78.0,62.0,77.0,73.0,26.0
6,Mexico,Korea Republic,0,1,24.0,15.0,71.0,64.0,75.0,62.0,...,27.0,56.0,9.0,72.0,67.0,78.0,62.0,77.0,73.0,26.0
7,Bosnia-Herzegovina,Japan,2,2,16.0,1.0,73.0,66.0,79.0,61.0,...,27.0,44.0,5.0,72.0,66.0,74.0,63.0,73.0,72.0,27.0
8,England,Uruguay,2,1,10.0,14.0,75.0,68.0,81.0,64.0,...,26.0,6.0,12.0,72.0,66.0,80.0,65.0,77.0,74.0,28.0
9,Iran,Costa Rica,3,2,49.0,4.0,67.0,60.0,75.0,58.0,...,28.0,13.0,4.0,66.0,60.0,76.0,57.0,74.0,67.0,27.0

In [33]:
dependent_data_train.head(10)

  Hasil
0     0
1     1
2     0
3     2
4     1
5     1
6     2
7     0
8     1
9     1

###### Keterangan
* Hasil Draw dilabeli 0
* Hasil Home Win dilabeli 1
* Hasil Away Win dilabeli 2

In [34]:
independent_data_test,dependent_data_test= preprocessingData(data_test_world_cup_2014)

[SoftImpute] Max Singular Value of X_init = 1673.849094
[SoftImpute] Iter 1: observed MAE=2.213644 rank=4
[SoftImpute] Iter 2: observed MAE=2.211457 rank=4
[SoftImpute] Iter 3: observed MAE=2.210880 rank=4
[SoftImpute] Iter 4: observed MAE=2.210847 rank=4
[SoftImpute] Iter 5: observed MAE=2.211146 rank=4
[SoftImpute] Iter 6: observed MAE=2.211658 rank=4
[SoftImpute] Iter 7: observed MAE=2.212369 rank=4
[SoftImpute] Iter 8: observed MAE=2.213274 rank=4
[SoftImpute] Iter 9: observed MAE=2.214269 rank=4
[SoftImpute] Iter 10: observed MAE=2.215468 rank=4
[SoftImpute] Iter 11: observed MAE=2.216847 rank=4
[SoftImpute] Iter 12: observed MAE=2.218229 rank=4
[SoftImpute] Iter 13: observed MAE=2.219767 rank=4
[SoftImpute] Iter 14: observed MAE=2.221499 rank=4
[SoftImpute] Iter 15: observed MAE=2.223499 rank=4
[SoftImpute] Iter 16: observed MAE=2.226016 rank=4
[SoftImpute] Iter 17: observed MAE=2.229713 rank=4
[SoftImpute] Iter 18: observed MAE=2.233836 rank=4
[SoftImpute] Iter 19: observed MAE=2.237575 rank=4
[SoftImpute] Iter 20: observed MAE=2.240254 rank=4
[SoftImpute] Iter 21: observed MAE=2.241742 rank=4
[SoftImpute] Iter 22: observed MAE=2.240843 rank=4
[SoftImpute] Iter 23: observed MAE=2.238267 rank=4
[SoftImpute] Iter 24: observed MAE=2.235421 rank=4
[SoftImpute] Iter 25: observed MAE=2.233123 rank=4
[SoftImpute] Iter 26: observed MAE=2.231467 rank=4
[SoftImpute] Iter 27: observed MAE=2.230493 rank=4
[SoftImpute] Iter 28: observed MAE=2.229886 rank=4
[SoftImpute] Stopped after iteration 28 for lambda=33.476982

C:\Users\Wahyu Nainggolan\Anaconda3\lib\site-packages\fancyimpute\soft_impute.py:100: RuntimeWarning: divide by zero encountered in double_scalars
  return (np.sqrt(ssd) / old_norm) < self.convergence_threshold

In [35]:
independent_data_test.head(10)

,home_team,away_team,home_score,away_score,HTRF,THFP,PHPAR,PHSPAR,PHPSAR,PHDAR,...,PHAAR,ATRF,TAFP,PAPAR,PASPAR,PAPSAR,PADAR,PATSA,PADBAR,PAAAR
0,Brazil,Colombia,2,1,11.0,20.0,76.0,70.0,80.0,65.0,...,28.0,4.0,5.0,73.0,67.0,80.0,63.0,79.0,75.0,27.0
1,Mexico,Cameroon,1,0,24.0,15.0,71.0,64.0,75.0,62.0,...,27.0,59.0,7.0,69.0,64.0,81.0,63.0,81.0,74.0,26.0
2,Spain,Netherlands,1,5,1.0,14.0,81.0,71.0,79.0,67.0,...,28.0,8.0,10.0,74.0,68.0,80.0,63.0,78.0,75.0,26.0
3,Chile,Australia,3,1,12.0,9.0,73.0,68.0,76.0,64.0,...,28.0,57.0,4.0,71.0,64.0,78.0,62.0,76.0,71.0,26.0
4,Colombia,Greece,3,0,4.0,5.0,73.0,67.0,80.0,63.0,...,27.0,18.0,3.0,73.0,66.0,79.0,62.0,76.0,74.0,28.0
5,Uruguay,Costa Rica,1,3,6.0,12.0,72.0,66.0,80.0,65.0,...,28.0,13.0,4.0,66.0,60.0,76.0,57.0,74.0,67.0,27.0
6,England,Italy,1,2,10.0,14.0,75.0,68.0,81.0,64.0,...,26.0,9.0,18.0,76.0,68.0,81.0,66.0,77.0,75.0,27.0
7,Ivory Coast,Japan,2,1,17.0,3.0,72.0,65.0,80.0,62.0,...,27.0,44.0,5.0,72.0,66.0,74.0,63.0,73.0,72.0,27.0
8,Switzerland,Ecuador,2,1,7.0,10.0,72.0,66.0,80.0,65.0,...,26.0,22.0,3.0,70.0,65.0,77.0,57.0,80.0,75.0,27.0
9,France,Honduras,3,0,21.0,14.0,76.0,69.0,80.0,68.0,...,26.0,34.0,3.0,70.0,62.0,78.0,60.0,77.0,72.0,28.0

In [36]:
dependent_data_test.head(10)

  Hasil
0     0
1     1
2     0
3     2
4     1
5     1
6     2
7     0
8     1
9     1

###### Keterangan
* Hasil Draw dilabeli 0
* Hasil Home Win dilabeli 1
* Hasil Away Win dilabeli 2

In [37]:
# One Hot Encoder 
dependent_data_train=preprocessingData_onehotencoder(dependent_data_train)
dependent_data_test=preprocessingData_onehotencoder(dependent_data_test)